
# Site settings
title: Ruichen Ma
name: Ruichen Ma
subtitle:  Scholar
email: 1396698241@qq.com
description: >
   Economist
baseurl: ""
url: "https://1396698241.github.io/"
github_username:  1396698241
disqus_baseurl: "https://1396698241.github.io/"
disqus_shortname: https-pesoto-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Ruichen Ma"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: 1396698241
    url: https://1396698241.github.io/
    desc: Fork me on GitHub
    share: false
